import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { AR_One_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ContextProvider from "@/components/context-provider";

const font = AR_One_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <ContextProvider>
            <Toaster richColors position="top-right" />
            {children}
          </ContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
