import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import { Pathway_Extreme } from "next/font/google";
import "./globals.css";

const pathway_extreme = Pathway_Extreme({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={pathway_extreme.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
